[package]
name = "check_nif"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] } # For making HTTP requests
scraper = "0.19"                                        # For parsing HTML